### ISSUE TITLE
SignetのPowLimit

### ISSUE THREAD

**Issue by monacoin-core** [monasuite/monad#7]
https://github.com/monasuite/monad/blob/e76faf19a82e5dffbed637840a4683ef3260e6fa/chaincfg/params.go#L47

`	sigNetPowLimit = new(big.Int).Sub(new(big.Int).Lsh(bigOne, 236), bigOne)`

ここは省エネマイニングのために、あと8bit分大きく(236 -> 244)しておいた方がよいと思います。

**Comment by monacoin-core** [comment]
@wakiyamap 何の反応もないのはどうかと思うよ。
クローズしておきます。

**Comment by wakiyamap** [comment]
あーすみません。気づきませんでした。
まだテスト中のブランチなので、最終的にはcommit一個でmainブランチにコミットする予定です。
参考にさせていただきます。ありがとうございます！
